---
apiVersion: apps/v1

kind: Deployment

metadata:

  name: frontend-deployment

  namespace: egs2

spec:

  selector:

    matchLabels:

      app: frontend-deployment

  replicas: 1

  template:

    metadata:

      labels:

        app: frontend-deployment

    spec:

      containers:

      - name: frontend

        image: registry.deti:5000/egs2/frontendbrasa:v9

        ports:

        - containerPort: 3000

---

apiVersion: v1

kind: Service

metadata:

  name: frontend-service

  namespace: egs2

spec:

  ports:

  - protocol: TCP

    port: 3000

    targetPort: 3000  

  selector:

    app: frontend-deployment

  type: NodePort
  
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: egs2
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  rules:
  - host: pchinchaloja.k3s
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port: 
              number: 3000
      - path: /*
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 3000
---
