---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authserver-deployment
  namespace: egs2
spec:
  selector:
    matchLabels:
      app: authserver-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: authserver-deployment
    spec:
      containers:
      - name: authserver-deployment
        image: registry.deti:5000/egs2/authservice:v3
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: authserver-service
  namespace: egs2
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: authserver-deployment
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authserver-ingress
  namespace: egs2
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  rules:
  - host: danimag-authserver.k3s
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: authserver-service
            port: 
              number: 8080
