---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodbauth
  namespace: egs2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodbauth
  template:
    metadata:
      labels:
        app: mongodbauth
    spec:
      containers:
      - name: mongodbauth
        image: registry.deti:5000/egs2/mongoauth:210622
        ports: 
        - containerPort: 27017
        env:         
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom: 
            secretKeyRef:
              name: mongodb-secret-auth
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mongodb-secret-auth
              key: mongo-root-password
      volumes:
        - name: mongodb-persitent-storage-auth
          persistentVolumeClaim:
            claimName: mongodb-pv-auth
---
apiVersion: v1
kind: Service
metadata:
  name: mongoauthservice
  namespace: egs2
spec:
  selector:
    app: mongodbauth
  ports:
    - protocol: TCP              
      port: 27017
      targetPort: 27017
