---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deploymentwh
  namespace: egs2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb1
  template:
    metadata:
      labels:
        app: mongodb1
    spec:
      containers:
      - name: mongodb
        image: registry.deti:5000/egs2/mongo_wh
        ports: 
        - containerPort: 27017
        env:         
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom: 
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
      volumes:
        - name: mongodb-persitent-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc-warehouse
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: egs2
spec:
  selector:
    app: mongodb1
  ports:
    - protocol: TCP              
      port: 27017
      targetPort: 27017
